### ISSUE TITLE
Twitter Assignment Submission

### ISSUE THREAD

**Issue by henryou007** [henryou007/Twitter#1]
@codepathreview @codepath

**Comment by codepathreview** [comment]
Hi Henry,

:+1: nice work. The point of this homework was to explore some challenges involved in developing a richer MVC client. A few notes after checking out the code:
- For TweetTableViewCell, you should move all unnecessarily public properties to the private class extension in the .m file.
- Good coding style for the properties. The compiler generates important things in the getters and setters that get circumvented when the instance variables are used directly (the variables that are prefixed with underscore). Always use self.property to access a property.
- Nice work specifying the Auto Layout constraints.
- Note that you should try handling the conditionally present retweet label in the cells. This is a situation where its not possible to specify the behavior that you want solely using Interface Builder.
- Nice work setting up the controls within the Tweet cells. It can sometimes be hard to have a clean design for embedded controls because it usually involves cumbersome plumbing. This is an instance where I think having the model handle the network action helps greatly simplify the implementation.
- You should consider using Mantle, it's a lightweight ORM that eliminates a lot of boilerplate, and it's also compatible with Core Data if your project requires that.
- You should try implementing the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience.
