### ISSUE TITLE
Twitter Second Iteration Submission 

### ISSUE THREAD

**Issue by henryou007** [henryou007/Twitter#2]
@codepathreview @codepath

**Comment by codepathreview** [comment]
Hi Henry,

Nice work! We added this homework so that you'll have the experience building an app that's more similar in complexity to a production app. It's also useful to have practical experience building a container view controller, which is a more advanced topic. The optional account switching feature is interesting because you have to think about how TwitterClient is caching the access token to make sure it works correctly for multiple accounts. Displaying the account switching screen is implemented using custom view controller transitions.

A few notes after checking out the code:
- Nice work encapsulating the properties into the private class extension.
- Good coding style for the properties. The compiler generates important things in the getters and setters that get circumvented when the instance variables are used directly (the variables that are prefixed with underscore). Always use self.property to access a property.
- You should always specify Auto Layout constraints in your nibs.
- Note that you should resolve all the Auto Layout constraint warnings in your nibs.
- Consider refactoring the profile view controller so that it shares code with the TimelineViewController. There are two general strategies: you can subclass the TimelineViewController or create a separate class called a TimelineController (not a view controller). TimelineController is a dataSource and a delegate to a UITableView and knows how to show a feed of tweets.
- Nice work encapsulating the properties of the custom cells that you added.
- Nice work abstracting the hamburger controller so that it can be reused in other applications.
- You should consider implementing the blurred table view header. There are several approaches here that are all valid. You can implement the header has a table header, a section header, or a cell. My preferred approach is to implement it as a table header, it's the easiest way to flow the image above the content. These detail touches are where you really learn the nooks and crannies of the framework.
